### ISSUE TITLE
Unable to connect to ClamAV server

### ISSUE THREAD

**Issue by sandip-divii** [appwrite/php-clamav#12]
I am using windows 10. I followed installation procedure through composer and created a file to execute. But getting this problem.

`Fatal error: Uncaught RuntimeException: Unable to connect to ClamAV server in C:\xampp\htdocs\test\scan\appwrite\vendor\appwrite\php-clamav\src\ClamAV\Network.php:48 Stack trace: #0 C:\xampp\htdocs\test\scan\appwrite\vendor\appwrite\php-clamav\src\ClamAV\ClamAV.php(33): Appwrite\ClamAV\Network->getSocket() #1 C:\xampp\htdocs\test\scan\appwrite\vendor\appwrite\php-clamav\src\ClamAV\ClamAV.php(51): Appwrite\ClamAV\ClamAV->sendCommand('PING') #2 C:\xampp\htdocs\test\scan\appwrite\index.php(9): Appwrite\ClamAV\ClamAV->ping() #3 {main} thrown in C:\xampp\htdocs\test\scan\appwrite\vendor\appwrite\php-clamav\src\ClamAV\Network.php on line 48`

**Comment by TorstenDittmann** [comment]
hey 👋🏻 

Can you share your code?
