### ISSUE TITLE
🚀 Feature: Laravel integration

### ISSUE THREAD

**Issue by raonikhil** [appwrite/php-clamav#22]
### 🔖 Feature description

It would be ideal to make a package for laravel

### 🎤 Pitch

Laravel being the most popular framework, many developers could benefit from it.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by TorstenDittmann** [comment]
Hey :)

How would a package for Laravel look different from the current implementation?
