### ISSUE TITLE
📚 Documentation: Specify which filescan() return bool corresponds to infection

### ISSUE THREAD

**Issue by grickard** [appwrite/php-clamav#29]
### 💭 Description

Thank you for this integration!

Presently the documentation simply states:

> // Return true of false for file scan

In my opinion, it would be more intuitive to specify which bool return value indicates infected vs not. So maybe revise this line to say:

> // Returns **true** if a file is clean or **false** if a file is infected

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by joeyouss** [comment]
Thank you for bringing this up.
